webpack_encore:
  # The path where Encore serves the built assets (Encore.setOutputPath())
  output_path: '%kernel.project_dir%/public/build'


framework:
  assets:
    json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'