monolog:
  channels:
    - deprecations
  handlers:
    main:
      type: stream
      path: "php://stdout"
      level: debug
      channels: [ "!event" ]
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine", "!console" ]
    deprecation:
      type: stream
      channels: [ deprecation ]
      path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"